name: Update Prediksi Harian

on:
  schedule:
    - cron: '0 1 * * *' # tiap jam 1 dini hari UTC (08:00 WIB)
  workflow_dispatch:

jobs:
  update-prediksi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate prediksi sederhana
        run: |
          date=$(date -u +'%Y-%m-%d')
          harga=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd" | jq '.bitcoin.usd')
          # contoh logika sederhana: prediksi naik kalau harga > 30000
          if (( $(echo "$harga > 30000" | bc -l) )); then
            prediksi="🚀 Naik moderat"
          else
            prediksi="📉 Turun ringan"
          fi
          echo "{\"date\": \"$date\", \"prediksi\": \"$prediksi\"}" > prediksi.json

      - name: Commit dan push perubahan
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add prediksi.json
          git commit -m "Update prediksi otomatis $date" || echo "No changes"
          git push
