name: Update Sinyal Harian

on:
  schedule:
    - cron: '0 1 * * *'  # 08:00 WIB
  workflow_dispatch:

jobs:
  update-sinyal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: node generate-sinyal.js

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sinyal.json
          git commit -m "Update sinyal harian"
          git push
