name: Update Sinyal Harian

on:
  schedule:
    - cron: '0 1 * * *'  # Setiap hari jam 08:00 WIB (01:00 UTC)
  workflow_dispatch:      # Bisa dijalankan manual juga

jobs:
  update-sinyal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Jalankan generate-sinyal.js
        run: node generate-sinyal.js

      - name: Commit & Push hasil
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sinyal.json
          git commit -m "Update sinyal harian" || echo "Ga ada yang berubah"
          git pull --rebase
          git push
